### ISSUE TITLE
Crash With Sound

### ISSUE THREAD

**Issue by Christofosho** [Open-RSC/Game#536]
**Describe the bug**
Sold a couple of items to the Varrock General Store, and crashed each time.

```
     [java] java.lang.NullPointerException
     [java] 	at com.openrsc.client.data.DataOperations.getUnsigned2Bytes(DataOperations.java:38)
     [java] 	at com.openrsc.client.data.DataOperations.getDataFileLength(DataOperations.java:212)
     [java] 	at rsc.mudclient.playSoundFile(mudclient.java:12334)
     [java] 	at rsc.mudclient.handlePacket2(mudclient.java:10776)
     [java] 	at rsc.mudclient.handlePacket1(mudclient.java:9891)
     [java] 	at rsc.mudclient.checkConnection(mudclient.java:1268)
     [java] 	at rsc.mudclient.handleGameInput(mudclient.java:8054)
     [java] 	at rsc.mudclient.update(mudclient.java:13346)
     [java] 	at rsc.mudclient.run(mudclient.java:373)
     [java] 	at java.lang.Thread.run(Thread.java:748)
     [java] rsc.util.RSRuntimeError
     [java] 	at rsc.util.GenUtil.makeThrowable(GenUtil.java:72)
     [java] 	at rsc.mudclient.playSoundFile(mudclient.java:12345)
     [java] 	at rsc.mudclient.handlePacket2(mudclient.java:10776)
     [java] 	at rsc.mudclient.handlePacket1(mudclient.java:9891)
     [java] 	at rsc.mudclient.checkConnection(mudclient.java:1268)
     [java] 	at rsc.mudclient.handleGameInput(mudclient.java:8054)
     [java] 	at rsc.mudclient.update(mudclient.java:13346)
     [java] 	at rsc.mudclient.run(mudclient.java:373)
     [java] 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by Christofosho** [comment]
This has to do with sound - keeping open for now until sound is fixed back up.

**Comment by Christofosho** [comment]
#677
